-- =====================================================================
-- MRI Radiology Database — Database Schema
-- DBMS: MySQL / MariaDB
-- Normalization: Third Normal Form (3NF)
--
-- Phase 2 — Database Design
-- Based on the mapping specification from Phase 1 (EERD + Mapping)
--
-- Database Structure:
-- PATIENT -> STUDY -> SERIES -> MRI_IMAGE
-- PATIENT -> RADIOLOGY_REPORT
-- =====================================================================

CREATE DATABASE IF NOT EXISTS mri_radiology_db
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE mri_radiology_db;


-- ---------------------------------------------------------------------
-- 1. PATIENT
--
-- patient_id is obtained from the patient directory name in the
-- MRI_Data dataset (e.g., "0001") and corresponds to the
-- "Patient ID" column in the Radiologists Report dataset.
-- ---------------------------------------------------------------------
CREATE TABLE patient (
    patient_id      VARCHAR(10)     NOT NULL,

    CONSTRAINT pk_patient
        PRIMARY KEY (patient_id),

    CONSTRAINT chk_patient_id_format
        CHECK (patient_id REGEXP '^[0-9]+$')
) ENGINE=InnoDB;


-- ---------------------------------------------------------------------
-- 2. RADIOLOGY_REPORT
--
-- Each patient has at most one radiology report in the source
-- Radiologists Report dataset.
--
-- report_id is automatically generated by the database using
-- AUTO_INCREMENT.
-- clinician_notes contains the radiologist's clinical notes
-- extracted from the source Excel file.
-- ---------------------------------------------------------------------
CREATE TABLE radiology_report (
    report_id       INT             NOT NULL AUTO_INCREMENT,
    patient_id      VARCHAR(10)     NOT NULL,
    clinician_notes TEXT            NULL,

    CONSTRAINT pk_report
        PRIMARY KEY (report_id),

    CONSTRAINT uq_report_patient
        UNIQUE (patient_id),

    CONSTRAINT fk_report_patient
        FOREIGN KEY (patient_id)
        REFERENCES patient(patient_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB;


-- ---------------------------------------------------------------------
-- 3. STUDY
--
-- study_id is an internal identifier automatically generated by
-- the database.
--
-- study_name is obtained from the name of the study directory,
-- for example:
-- "L-SPINE_LSS_20160309_091629_240000"
--
-- study_date is extracted from the date encoded in study_name.
-- For example, "20160309" is converted to "2016-03-09".
-- ---------------------------------------------------------------------
CREATE TABLE study (
    study_id        INT             NOT NULL AUTO_INCREMENT,
    patient_id      VARCHAR(10)     NOT NULL,
    study_name      VARCHAR(255)    NOT NULL,
    study_date      DATE            NULL,

    CONSTRAINT pk_study
        PRIMARY KEY (study_id),

    CONSTRAINT uq_study_per_patient
        UNIQUE (patient_id, study_name),

    CONSTRAINT fk_study_patient
        FOREIGN KEY (patient_id)
        REFERENCES patient(patient_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB;


-- ---------------------------------------------------------------------
-- 4. SERIES
--
-- series_id is an internal identifier automatically generated by
-- the database.
--
-- series_name is obtained from the name of the series directory.
--
-- sequence_type and orientation are extracted from series_name.
-- For example:
--
-- "T2_TSE_SAG_384_0002"
--     -> sequence_type = "T2"
--     -> orientation   = "SAG"
--
-- For LOCALIZER series, sequence_type and orientation may be NULL
-- because these attributes cannot be reliably determined from
-- the series name.
-- ---------------------------------------------------------------------
CREATE TABLE series (
    series_id       INT             NOT NULL AUTO_INCREMENT,
    study_id        INT             NOT NULL,
    series_name     VARCHAR(255)    NOT NULL,
    sequence_type   VARCHAR(50)     NULL,
    orientation     VARCHAR(10)     NULL,

    CONSTRAINT pk_series
        PRIMARY KEY (series_id),

    CONSTRAINT uq_series_per_study
        UNIQUE (study_id, series_name),

    CONSTRAINT fk_series_study
        FOREIGN KEY (study_id)
        REFERENCES study(study_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT chk_orientation
        CHECK (
            orientation IS NULL
            OR orientation IN ('SAG', 'TRA', 'COR')
        )
) ENGINE=InnoDB;


-- ---------------------------------------------------------------------
-- 5. MRI_IMAGE
--
-- image_id is an internal identifier automatically generated by
-- the database. It is globally unique across the entire table and
-- does not reset when a new study or series is encountered.
--
-- file_name stores the original image file name.
-- file_path stores the path to the physical image file.
--
-- The actual MRI image files are stored in the file system rather
-- than directly in the database. The database stores only their
-- metadata and file locations.
-- ---------------------------------------------------------------------
CREATE TABLE mri_image (
    image_id        INT             NOT NULL AUTO_INCREMENT,
    series_id       INT             NOT NULL,
    file_name       VARCHAR(255)    NOT NULL,
    file_path       VARCHAR(500)    NOT NULL,

    CONSTRAINT pk_image
        PRIMARY KEY (image_id),

    CONSTRAINT uq_image_path
        UNIQUE (file_path),

    CONSTRAINT fk_image_series
        FOREIGN KEY (series_id)
        REFERENCES series(series_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE image_feature (
    image_id        INT NOT NULL,
    feature_vector  JSON NOT NULL,

    CONSTRAINT pk_image_feature
        PRIMARY KEY (image_id),

    CONSTRAINT fk_feature_image
        FOREIGN KEY (image_id)
        REFERENCES mri_image(image_id)
        ON DELETE CASCADE
) ENGINE=InnoDB;
-- =====================================================================
-- INDEXES
--
-- The following indexes support common access patterns in
-- Applications 1 and 2, including:
--   1. Searching studies by patient ID
--   2. Searching studies by study date
--   3. Searching series by study ID
--   4. Filtering series by sequence type
--   5. Filtering series by orientation
--   6. Retrieving images belonging to a specific series
--
-- These indexes will also be used as the basis for the
-- Indexing and Query Processing & Optimization experiments.
-- =====================================================================

CREATE INDEX idx_study_patient
    ON study(patient_id);

CREATE INDEX idx_study_date
    ON study(study_date);

CREATE INDEX idx_series_study
    ON series(study_id);

CREATE INDEX idx_series_sequence_type
    ON series(sequence_type);

CREATE INDEX idx_series_orientation
    ON series(orientation);

CREATE INDEX idx_image_series
    ON mri_image(series_id);